# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$character\
$directory\
[⚡️](fg:#ffffff)\
$git_branch\
$nodejs\
$python\
$conda\
$golang\
$rust\
[❯](fg:#9ECE6A)
"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "fg:#BB9AF7"
truncation_length = 1

[git_branch]
symbol = ""
style = "fg:#f7768e"
format = '[\($symbol $branch\)]($style)'

[nodejs]
symbol = "󰎙"
format = ' [$symbol ($version )]($style)'

[python]
symbol = "\ue235"
format = ' [${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[conda]
symbol = "\ue235"
format = ' [${symbol} ${environment} ]($style)'


[golang]
symbol = "󰟓"
format = ' [$symbol ($version )]($style)'

[rust]
symbol = "󱘗"
format = ' [$symbol ($version )]($style)'
