# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = """
# $character\
# $directory\
# [⚡️](fg:#cdd6f4)\
# $git_branch\
# $nodejs\
# $python\
# $conda\
# $golang\
# $rust\
# [❯](fg:#a6e3a1)
# """
format = """
$directory\
$git_branch\
$python\
[❯](fg:#76946A) 
"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](#76946A)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "fg:#957FB8"
truncation_length = 1

[git_branch]
symbol = ""
style = "fg:#C0A36E"
format = '[\($symbol $branch\) ]($style)'

[nodejs]
symbol = "󰎙"
format = ' [$symbol ($version )]($style)'

[python]
symbol = "\ue235"
format = '[(${symbol} $virtualenv )]($style)'

[conda]
symbol = "\ue235"
format = ' [${symbol} ${environment} ]($style)'


[golang]
symbol = "󰟓"
format = ' [$symbol ($version )]($style)'

[rust]
symbol = "󱘗"
format = ' [$symbol ($version )]($style)'
